/*
 * Copyright (c) 2023 Martin Geisse
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
package name.martingeisse.grumpyjson.registry;

import name.martingeisse.grumpyjson.AdapterProxy;
import name.martingeisse.grumpyjson.JsonTypeAdapter;
import name.martingeisse.grumpyjson.RecordAdapter;

import java.lang.reflect.ParameterizedType;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Base class for a registry which acts somewhat like a {@link Map}, but with the following differences:
 * <ul>
 *     <li>Each registrable ("value" in Map terminology) knows the keys it supports, i.e. the keys that can be
 *     used to obtain that registrable from the registry. Regitrables can be added without specifying a key, and a
 *     registrable will be available using any of the keys it supports.</li>
 *     <li>Depending on the subclass, the registry may support auto-generation of a registrable for a key for which no
 *     registrable was registered manually.</li>
 *     <li>The only allowed ways to manipulate the registry are adding registrables manually, auto-generation, and
 *     clearing the registry. In particular, removing individual registrables is not supported.</li>
 *     <li>The only possible way to query the registry is to ask whether a key is supported, and to get the registrable
 *     for a key. In particular, iteration is not supported.</li>
 *     <li>The registry operates in two phases, configuration phase and run-time phase. In the configuration phase, only
 *     registering objects and clearing the registry are allowed. Querying the registry is not allowed. In the
 *     run-time phase, only querying is allowed, no manipulation. The transition from configuration phase to
 *     run-time phase is called "sealing" the registry. The separation into two phases allows internal optimization.
 *     </li>
 *     <li>Registrables have an {@link Registrable#initialize(Registrable.InitializationContext)} method that will be
 *     called to resolve dependencies on other registrables.</li>
 * </ul>
 *
 * @param <K> the key type
 * @param <V> the type of registrable stored in this registry
 */
/*
    PROBLEM: How to auto-generate a registrable that can be used for *other* keys (e.g. RecordAdapter for Foo<String>
    can be used for raw Foo.class too) but avoid generating it twice if both are requested in parallel. The easiest
        thing would actually be to allow duplicate generation. We can even guarantee that only one of them will be used,
    except that the other must still provide supports(key) -- that is the only method that must always work.

    make the list of registrables a concurrency safe list
    add a set of "keys for which a registrable has been appended to this list"
    MUST BE UPDATED TOGETHER, ATOMICALLY!
        This set ensures that we don't add lots of unnecessary registrables
    for a new key: create and append to list, if not yet happened according to the set; update set if added
    then scan the list for the first matching registrable (may be a different one!)
        add to the map for that key
        initialize (thread safe way)
            use
    disadvantage: keeps unnecessary registrables around. May consume memory.
        Possible remedy: if searching the list after adding yields a different one, remove the added one / turn into
        empty shell (more threadsafe) to reclaim memory


        ALTERNATIVE: only manually added regitrables can handle multiple keys. autogenerated ones always handle a single key.
    -> only works if the generator is internally optimized! generic records!
    - this is actually a good solution and exactly matches the problem: I only need record adapters generated, and I
    can synchronize the factory internally.
    - the current solution is even worse. It just creates the record adapter once per type argument.


    JUST use abstract methods to abstract from auto-generation for now. No interface. This can easily be added later
    if users want to provide their own factories. The main synchronization problem can be solved around abstract
    methods just as well.

    The knownMap and initializedMap may contain null values for keys that are not supported by any added or
    auto-generatable registrable. This optimizes and simplifies the negative case.


Do we need initialization at all? The mechanism is nice and I should keep it in git if needed some day, but right now,
it isn't used at all. Rather, the registrables keep a reference to the registry to ask for other registrables at
*run-time*, and they expect those dependencies to be ready to use ("initialized"). I could just give them a reference
to the registry (possibly abstracted) to obtain fully ready registrables, and use the sealed flag to prevent mis-use.

But how do I give them that reference? initialization. Or demand that it gets passed in the constructor.
-> misuse in the constructor is not a real concern. Either it's configuration phase, or it immediately causes
infinite recursion (fails fast), or it works. Initialization might be desired later to reduce coupling, but for now
passing the registry in the constructor is sufficient. But keep it in git.

 */
public abstract class Registry<K, V extends Registrable<K, V>> {

    private final List<V> manuallyAddedRegistrables = new ArrayList<>();
    private final AtomicBoolean sealedFlag = new AtomicBoolean(false);
    private final List<RegistrableWrapper<K, V>> wrappedManuallyAddedRegistrables = new ArrayList<>();
    private final ConcurrentMap<K, RegistrableWrapper<K, V>> knownMap = new ConcurrentHashMap<>();
    private final ConcurrentMap<K, V> initializedMap = new ConcurrentHashMap<>();
    private final Registrable.InitializationContext<K, V> initializationContext = (K key) -> knownmap;

    // ----------------------------------------------------------------------------------------------------------------
    // configuration-time methods
    // ----------------------------------------------------------------------------------------------------------------

    /**
     * Throws an {@link IllegalStateException} if this registry has been sealed already.
     */
    protected final void ensureConfigurationPhase() {
        if (sealedFlag.get()) {
            throw new IllegalStateException("this registry has been sealed already");
        }
    }

    /**
     * Removes all registered objects from this registry. This is useful because the registries used by grumpyjson
     * contain default registrables, and the code using it might not want to use them.
     */
    public final void clear() {
        ensureConfigurationPhase();
        manuallyAddedRegistrables.clear();
    }

    /**
     * Registers a registrable with this registry.
     *
     * @param registrable the registrable to add
     */
    public final void register(V registrable) {
        Objects.requireNonNull(registrable, "registrable");
        ensureConfigurationPhase();
        manuallyAddedRegistrables.add(registrable);
    }

    /**
     * Seals this registry, moving from the configuration phase to the run-time phase.
     */
    public final void seal() {
        ensureConfigurationPhase();
        sealedFlag.set(true);
        for (V registrable : manuallyAddedRegistrables) {
            wrappedManuallyAddedRegistrables.add(new RegistrableWrapper<>(null, registrable));
        }
    }


    // ----------------------------------------------------------------------------------------------------------------
    // run-time methods
    // ----------------------------------------------------------------------------------------------------------------

    /**
     * Throws an {@link IllegalStateException} if this registry has not yet been sealed.
     */
    protected final void ensureRunTimePhase() {
        if (!sealedFlag.get()) {
            throw new IllegalStateException("this registry has not yet been sealed");
        }
    }

    /**
     * Checks whether the specified key is supported by any registrable that is registered with this registry or can be
     * auto-generated on the fly.
     * <p>
     * Note that there are some reasons why a registered object may claim to support a key, but fail at run-time when it
     * actually encounters that key. Such a key will still be "supported" by that registrable from the point-of-view of
     * the registry. Refer to the documentation of the individual registrables for details.
     *
     * @param key the key to check
     * @return true if supported, false if not
     */
    public final boolean supports(K key) {
        Objects.requireNonNull(key, "key");
        ensureRunTimePhase();
        return getOrNull(key) != null;
    }

    /**
     * Returns a registered object for the specified key, auto-generating it if necessary and possible. This method will
     * throw an exception if no registrable was registered manually that supports the key and no registrable can be
     * auto-generated. If multiple registrables have been registered that can handle the specified key, the one
     * registered earlier will take precedence.
     *
     * @param key the key to return a registrable for
     * @return the registered object, possibly auto-generated
     */
    public final V get(K key) {
        V result = getOrNull(key);
        if (result == null) {
            throw new RuntimeException(getErrorMessageForUnknownKey(key));
        }
        return result;
    }

    private V getOrNull(K key) {
        Objects.requireNonNull(key, "key");
        ensureRunTimePhase();

        // computeIfAbsent() cannot be used, if it behaves as it should, because recursively adding recognized keys
        // would cause a ConcurrentModificationException. Note that thread safety is not a concern here because,
        // while two threads might *both* decide to create a missing registrable, we just end up with either one of them
        // and they should be equivalent.
        V registrable = map.get(key);

        // check if one of the registered adapters supports this type
        if (registrable == null) {
            for (V registrableFromList : manuallyAddedRegistrables) {
                if (registrableFromList.supports(key)) {
                    registrable = registrableFromList;
                    map.put(key, registrable);
                    break;
                }
            }
        }

        // check if we can auto-generate an adapter
        if (registrable == null && supportsAutoGeneration(key)) {

            // Next, install a proxy, so that recursive types don't crash the registry. Note that we don't put the
            // adapter/proxy into the adapterList because we already put it into the adapterMap, and it cannot handle
            // any types other than the exact type it gets generated for.
            var proxy = new AdapterProxy<>();
            map.put(type, proxy);

            // finally, create the actual adapter and set it as the proxy's target
            if (type instanceof Class<?> clazz) {
                registrable = new RecordAdapter<>(clazz, this);
            } else if (type instanceof ParameterizedType parameterizedType) {
                registrable = new RecordAdapter<>((Class<?>)parameterizedType.getRawType(), this);
            } else {
                throw new RuntimeException("internal error: erroneously selected a record adapter for type " + type);
            }

            //noinspection unchecked
            proxy.setTarget((JsonTypeAdapter<Object>) registrable);

        }

        // if this failed, then we don't have an appropriate adapter
        return registrable;
    }

    /**
     * Auto-generates a registrable in a subclass-specific way. This method does not have to check the key for null,
     * nor whether this registry is in the configuration phase.
     * <p>
     * This method should not itself refer to the registry, to avoid infinite recursion. If the registrable has a
     * dependency on other registrables, it should resolve those dependencies in its
     * {@link Registrable#initialize(Registrable.InitializationContext)} method. That method should not be called by
     * the auto-generation. Instead, it will be called by the registry after auto-generation is complete and
     * <i>after</i> making it available as a dependency for other registrables.
     * <p>
     * The returned registrable will only be used for the specified key, not for other keys that it might support as
     * well. To re-use a single auto-generated registrable that supports multiple keys for all the keys it supports,
     * the auto-generation itself must return the same registrable for all those keys.
     *
     * @param key the key (never null)
     * @return the auto-generated registrable, or null if auto-generation is not supported for that key
     */
    protected abstract V generateRegistrable(K key);

    /**
     * Produces an error message that gets used in an exception for an unknown key. The error message is one of the
     * most frequent points of contact between the registry and application code, so it should be as developer-friendly
     * as possible.
     *
     * @param key the unknown key
     * @return the error message
     */
    protected abstract String getErrorMessageForUnknownKey(K key);

}
